// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClearlyEditable
{
    internal sealed partial class Vsix
    {
        public const string Id = "ClearlyEditable.d69d322e-f85a-47be-ac01-3d8f823db795";
        public const string Name = "Clearly Editable";
        public const string Description = @"Change the editor background color to show which documents can't or shouldn't be edited.";
        public const string Language = "en-US";
        public const string Version = "2.8.1";
        public const string Author = "Matt Lacey";
        public const string Tags = "editor";
    }
}
